package com.slideindex.app.gesture

import android.view.KeyEvent

data class KeyEventPresetItem(
    val keyCode: Int,
    val constantName: String,
    val labelZh: String,
    val category: KeyEventCategory,
    val description: String = "",
)

enum class KeyEventCategory(val titleZh: String) {
    SYSTEM("系统控制"),
    MEDIA("媒体与声音"),
    NAVIGATION("方向与网页导航"),
    INPUT_EDIT("输入与文本编辑"),
    HARDWARE("硬件与快捷应用"),
    TV_REMOTE("电视与智能遥控"),
    GAMEPAD("游戏与手柄按键"),
    FUNCTION_KEYS("功能键 (F1-F12)"),
}

object KeyEventPresets {
    val presets: List<KeyEventPresetItem> = listOf(
        // ==================== 1. 系统控制 ====================
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MENU,
            constantName = "KEYCODE_MENU",
            labelZh = "菜单键 (Menu)",
            category = KeyEventCategory.SYSTEM,
            description = "打开当前前台应用的选项菜单 (Option Menu)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_APP_SWITCH,
            constantName = "KEYCODE_APP_SWITCH",
            labelZh = "多任务 / 最近应用",
            category = KeyEventCategory.SYSTEM,
            description = "呼出系统任务切换器",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_HOME,
            constantName = "KEYCODE_HOME",
            labelZh = "主屏幕 (Home)",
            category = KeyEventCategory.SYSTEM,
            description = "回到系统桌面",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BACK,
            constantName = "KEYCODE_BACK",
            labelZh = "返回键 / 历史后退 (Back)",
            category = KeyEventCategory.SYSTEM,
            description = "系统返回上一层 / 历史栈后退 (Complement of KEYCODE_FORWARD)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_POWER,
            constantName = "KEYCODE_POWER",
            labelZh = "电源键 (Power)",
            category = KeyEventCategory.SYSTEM,
            description = "系统电源开关",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_SLEEP,
            constantName = "KEYCODE_SLEEP",
            labelZh = "屏幕休眠",
            category = KeyEventCategory.SYSTEM,
            description = "让设备屏幕进入睡眠休眠状态",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_WAKEUP,
            constantName = "KEYCODE_WAKEUP",
            labelZh = "唤醒屏幕",
            category = KeyEventCategory.SYSTEM,
            description = "点亮并唤醒休眠中的屏幕",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_SOFT_SLEEP,
            constantName = "KEYCODE_SOFT_SLEEP",
            labelZh = "软休眠 / 锁屏",
            category = KeyEventCategory.SYSTEM,
            description = "锁定屏幕进入待机",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_NOTIFICATION,
            constantName = "KEYCODE_NOTIFICATION",
            labelZh = "通知面板",
            category = KeyEventCategory.SYSTEM,
            description = "下拉展开系统通知面板",
        ),
        KeyEventPresetItem(
            keyCode = 312, // KeyEvent.KEYCODE_QUICK_SETTINGS
            constantName = "KEYCODE_QUICK_SETTINGS",
            labelZh = "快捷设置面板",
            category = KeyEventCategory.SYSTEM,
            description = "下拉展开系统快捷控制面板",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_SETTINGS,
            constantName = "KEYCODE_SETTINGS",
            labelZh = "系统设置",
            category = KeyEventCategory.SYSTEM,
            description = "打开系统主设置页面",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_SEARCH,
            constantName = "KEYCODE_SEARCH",
            labelZh = "搜索键",
            category = KeyEventCategory.SYSTEM,
            description = "触发全局搜索或应用内搜索",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_VOICE_ASSIST,
            constantName = "KEYCODE_VOICE_ASSIST",
            labelZh = "语音助手",
            category = KeyEventCategory.SYSTEM,
            description = "唤醒系统语音助理",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_SYSRQ,
            constantName = "KEYCODE_SYSRQ",
            labelZh = "系统截屏 (SysRq / PrintScreen)",
            category = KeyEventCategory.SYSTEM,
            description = "触发系统原生截屏",
        ),
        KeyEventPresetItem(
            keyCode = 297, // KEYCODE_ACCESSIBILITY_SHORTCUT
            constantName = "KEYCODE_ACCESSIBILITY_SHORTCUT",
            labelZh = "无障碍快捷键",
            category = KeyEventCategory.SYSTEM,
            description = "触发系统无障碍快捷功能",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_ALL_APPS,
            constantName = "KEYCODE_ALL_APPS",
            labelZh = "所有应用抽屉",
            category = KeyEventCategory.SYSTEM,
            description = "打开系统应用抽屉列表",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_WINDOW,
            constantName = "KEYCODE_WINDOW",
            labelZh = "画中画 / 窗口模式",
            category = KeyEventCategory.SYSTEM,
            description = "切换窗口显示模式",
        ),

        // ==================== 2. 媒体与声音 ====================
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_VOLUME_UP,
            constantName = "KEYCODE_VOLUME_UP",
            labelZh = "音量增大 (+)",
            category = KeyEventCategory.MEDIA,
            description = "增加系统音量",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_VOLUME_DOWN,
            constantName = "KEYCODE_VOLUME_DOWN",
            labelZh = "音量减小 (-)",
            category = KeyEventCategory.MEDIA,
            description = "降低系统音量",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_VOLUME_MUTE,
            constantName = "KEYCODE_VOLUME_MUTE",
            labelZh = "静音切换",
            category = KeyEventCategory.MEDIA,
            description = "开启或关闭系统静音",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MUTE,
            constantName = "KEYCODE_MUTE",
            labelZh = "麦克风/媒体静音",
            category = KeyEventCategory.MEDIA,
            description = "麦克风静音或媒体静音",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE,
            constantName = "KEYCODE_MEDIA_PLAY_PAUSE",
            labelZh = "播放 / 暂停",
            category = KeyEventCategory.MEDIA,
            description = "切换当前媒体播放/暂停状态",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_PLAY,
            constantName = "KEYCODE_MEDIA_PLAY",
            labelZh = "播放",
            category = KeyEventCategory.MEDIA,
            description = "开始播放媒体",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_PAUSE,
            constantName = "KEYCODE_MEDIA_PAUSE",
            labelZh = "暂停",
            category = KeyEventCategory.MEDIA,
            description = "暂停当前播放",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_NEXT,
            constantName = "KEYCODE_MEDIA_NEXT",
            labelZh = "下一曲",
            category = KeyEventCategory.MEDIA,
            description = "切换下一首歌曲或视频",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_PREVIOUS,
            constantName = "KEYCODE_MEDIA_PREVIOUS",
            labelZh = "上一曲",
            category = KeyEventCategory.MEDIA,
            description = "切换上一首歌曲或视频",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_FAST_FORWARD,
            constantName = "KEYCODE_MEDIA_FAST_FORWARD",
            labelZh = "快进",
            category = KeyEventCategory.MEDIA,
            description = "媒体播放快进",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_REWIND,
            constantName = "KEYCODE_MEDIA_REWIND",
            labelZh = "快退",
            category = KeyEventCategory.MEDIA,
            description = "媒体播放快退",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_STOP,
            constantName = "KEYCODE_MEDIA_STOP",
            labelZh = "停止播放",
            category = KeyEventCategory.MEDIA,
            description = "停止当前媒体播放",
        ),
        KeyEventPresetItem(
            keyCode = 272, // KeyEvent.KEYCODE_MEDIA_STEP_FORWARD
            constantName = "KEYCODE_MEDIA_STEP_FORWARD",
            labelZh = "单帧步进向前",
            category = KeyEventCategory.MEDIA,
            description = "媒体步进向前一帧/微小步进",
        ),
        KeyEventPresetItem(
            keyCode = 273, // KeyEvent.KEYCODE_MEDIA_STEP_BACKWARD
            constantName = "KEYCODE_MEDIA_STEP_BACKWARD",
            labelZh = "单帧步进向后",
            category = KeyEventCategory.MEDIA,
            description = "媒体步进向后一帧/微小步退",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_AUDIO_TRACK,
            constantName = "KEYCODE_MEDIA_AUDIO_TRACK",
            labelZh = "切换音轨",
            category = KeyEventCategory.MEDIA,
            description = "切换视频或多媒体音轨",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_EJECT,
            constantName = "KEYCODE_MEDIA_EJECT",
            labelZh = "弹出介质 (Eject)",
            category = KeyEventCategory.MEDIA,
            description = "弹出光驱或存储介质",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MEDIA_RECORD,
            constantName = "KEYCODE_MEDIA_RECORD",
            labelZh = "录音 / 录制",
            category = KeyEventCategory.MEDIA,
            description = "触发多媒体录制",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_HEADSETHOOK,
            constantName = "KEYCODE_HEADSETHOOK",
            labelZh = "耳机线控键 (Hook)",
            category = KeyEventCategory.MEDIA,
            description = "模拟耳机线控按键（接听/挂断/播控）",
        ),

        // ==================== 3. 方向与网页导航 ====================
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BACK,
            constantName = "KEYCODE_BACK",
            labelZh = "历史后退 / 返回 (Back)",
            category = KeyEventCategory.NAVIGATION,
            description = "浏览器历史后退 / 返回上一层 (Complement of KEYCODE_FORWARD)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_FORWARD,
            constantName = "KEYCODE_FORWARD",
            labelZh = "历史前进 (Forward)",
            category = KeyEventCategory.NAVIGATION,
            description = "浏览器或历史栈前进到下一页 (Complement of KEYCODE_BACK)",
        ),
        KeyEventPresetItem(
            keyCode = 260, // KeyEvent.KEYCODE_NAVIGATE_PREVIOUS
            constantName = "KEYCODE_NAVIGATE_PREVIOUS",
            labelZh = "上一导航项 (Navigate Previous)",
            category = KeyEventCategory.NAVIGATION,
            description = "UI 或列表中导航至上一个项目",
        ),
        KeyEventPresetItem(
            keyCode = 261, // KeyEvent.KEYCODE_NAVIGATE_NEXT
            constantName = "KEYCODE_NAVIGATE_NEXT",
            labelZh = "下一导航项 (Navigate Next)",
            category = KeyEventCategory.NAVIGATION,
            description = "UI 或列表中导航至下一个项目",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_REFRESH,
            constantName = "KEYCODE_REFRESH",
            labelZh = "刷新页面 (Refresh / F5)",
            category = KeyEventCategory.NAVIGATION,
            description = "刷新当前网页或视图",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BOOKMARK,
            constantName = "KEYCODE_BOOKMARK",
            labelZh = "打开书签",
            category = KeyEventCategory.NAVIGATION,
            description = "打开浏览器收藏书签",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_ZOOM_IN,
            constantName = "KEYCODE_ZOOM_IN",
            labelZh = "放大视图 (Zoom In)",
            category = KeyEventCategory.NAVIGATION,
            description = "页面或视图内容放大",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_ZOOM_OUT,
            constantName = "KEYCODE_ZOOM_OUT",
            labelZh = "缩小视图 (Zoom Out)",
            category = KeyEventCategory.NAVIGATION,
            description = "页面或视图内容缩小",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_DPAD_UP,
            constantName = "KEYCODE_DPAD_UP",
            labelZh = "方向键：上 (Up)",
            category = KeyEventCategory.NAVIGATION,
            description = "向上移动焦点或光标",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_DPAD_DOWN,
            constantName = "KEYCODE_DPAD_DOWN",
            labelZh = "方向键：下 (Down)",
            category = KeyEventCategory.NAVIGATION,
            description = "向下移动焦点或光标",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_DPAD_LEFT,
            constantName = "KEYCODE_DPAD_LEFT",
            labelZh = "方向键：左 (Left)",
            category = KeyEventCategory.NAVIGATION,
            description = "向左移动焦点或光标",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_DPAD_RIGHT,
            constantName = "KEYCODE_DPAD_RIGHT",
            labelZh = "方向键：右 (Right)",
            category = KeyEventCategory.NAVIGATION,
            description = "向右移动焦点或光标",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_DPAD_CENTER,
            constantName = "KEYCODE_DPAD_CENTER",
            labelZh = "居中确认 (DPad Center)",
            category = KeyEventCategory.NAVIGATION,
            description = "确定 / 点击当前焦点项",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_PAGE_UP,
            constantName = "KEYCODE_PAGE_UP",
            labelZh = "向上翻页 (Page Up)",
            category = KeyEventCategory.NAVIGATION,
            description = "屏幕或列表向上翻一页",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_PAGE_DOWN,
            constantName = "KEYCODE_PAGE_DOWN",
            labelZh = "向下翻页 (Page Down)",
            category = KeyEventCategory.NAVIGATION,
            description = "屏幕或列表向下翻一页",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MOVE_HOME,
            constantName = "KEYCODE_MOVE_HOME",
            labelZh = "跳至顶部 / 行首 (Move Home)",
            category = KeyEventCategory.NAVIGATION,
            description = "光标或视图跳至最顶端/最前端",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MOVE_END,
            constantName = "KEYCODE_MOVE_END",
            labelZh = "跳至底部 / 行尾 (Move End)",
            category = KeyEventCategory.NAVIGATION,
            description = "光标或视图跳至最底端/末尾",
        ),

        // ==================== 4. 输入与文本编辑 ====================
        KeyEventPresetItem(
            keyCode = 277, // KeyEvent.KEYCODE_CUT
            constantName = "KEYCODE_CUT",
            labelZh = "剪切 (Cut)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "剪切所选文本到剪贴板",
        ),
        KeyEventPresetItem(
            keyCode = 278, // KeyEvent.KEYCODE_COPY
            constantName = "KEYCODE_COPY",
            labelZh = "复制 (Copy)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "复制所选文本到剪贴板",
        ),
        KeyEventPresetItem(
            keyCode = 279, // KeyEvent.KEYCODE_PASTE
            constantName = "KEYCODE_PASTE",
            labelZh = "粘贴 (Paste)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "粘贴剪贴板中的内容",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_ENTER,
            constantName = "KEYCODE_ENTER",
            labelZh = "回车确认 (Enter)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "换行或确认发送",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_NUMPAD_ENTER,
            constantName = "KEYCODE_NUMPAD_ENTER",
            labelZh = "小键盘回车 (Numpad Enter)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "数字键盘确认",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_TAB,
            constantName = "KEYCODE_TAB",
            labelZh = "制表键 (Tab)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "跳转到下一个输入框或焦点",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_SPACE,
            constantName = "KEYCODE_SPACE",
            labelZh = "空格键 (Space)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "输入空格",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_DEL,
            constantName = "KEYCODE_DEL",
            labelZh = "退格删除 (Backspace)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "向前删除一个字符",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_FORWARD_DEL,
            constantName = "KEYCODE_FORWARD_DEL",
            labelZh = "前进删除 (Delete)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "向后删除一个字符",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CLEAR,
            constantName = "KEYCODE_CLEAR",
            labelZh = "清空 (Clear)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "清除当前输入内容",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_INSERT,
            constantName = "KEYCODE_INSERT",
            labelZh = "插入模式 (Insert)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "切换文本插入/覆盖模式",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CAPS_LOCK,
            constantName = "KEYCODE_CAPS_LOCK",
            labelZh = "大写锁定 (Caps Lock)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "切换大小写锁定",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_SCROLL_LOCK,
            constantName = "KEYCODE_SCROLL_LOCK",
            labelZh = "滚动锁定 (Scroll Lock)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "切换滚动锁定状态",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_NUM_LOCK,
            constantName = "KEYCODE_NUM_LOCK",
            labelZh = "数字键盘锁 (Num Lock)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "切换小键盘数字模式",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_LANGUAGE_SWITCH,
            constantName = "KEYCODE_LANGUAGE_SWITCH",
            labelZh = "切换输入法语言",
            category = KeyEventCategory.INPUT_EDIT,
            description = "切换键盘输入语言",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_ESCAPE,
            constantName = "KEYCODE_ESCAPE",
            labelZh = "退出键 (Esc)",
            category = KeyEventCategory.INPUT_EDIT,
            description = "退出当前模式或弹窗",
        ),

        // ==================== 5. 硬件与快捷应用 ====================
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CAMERA,
            constantName = "KEYCODE_CAMERA",
            labelZh = "相机快门 (Camera)",
            category = KeyEventCategory.HARDWARE,
            description = "打开相机或拍摄照片",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_FOCUS,
            constantName = "KEYCODE_FOCUS",
            labelZh = "相机对焦 (Focus)",
            category = KeyEventCategory.HARDWARE,
            description = "相机半按对焦",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CALL,
            constantName = "KEYCODE_CALL",
            labelZh = "拨号 / 接听电话 (Call)",
            category = KeyEventCategory.HARDWARE,
            description = "打开拨号盘或接听来电",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_ENDCALL,
            constantName = "KEYCODE_ENDCALL",
            labelZh = "挂断电话 (End Call)",
            category = KeyEventCategory.HARDWARE,
            description = "挂断当前通话",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BRIGHTNESS_UP,
            constantName = "KEYCODE_BRIGHTNESS_UP",
            labelZh = "屏幕亮度增大 (+)",
            category = KeyEventCategory.HARDWARE,
            description = "调高屏幕显示亮度",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BRIGHTNESS_DOWN,
            constantName = "KEYCODE_BRIGHTNESS_DOWN",
            labelZh = "屏幕亮度减小 (-)",
            category = KeyEventCategory.HARDWARE,
            description = "调低屏幕显示亮度",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CALCULATOR,
            constantName = "KEYCODE_CALCULATOR",
            labelZh = "打开计算器",
            category = KeyEventCategory.HARDWARE,
            description = "启动系统计算器应用",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CALENDAR,
            constantName = "KEYCODE_CALENDAR",
            labelZh = "打开日历",
            category = KeyEventCategory.HARDWARE,
            description = "启动系统日历应用",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_MUSIC,
            constantName = "KEYCODE_MUSIC",
            labelZh = "打开音乐",
            category = KeyEventCategory.HARDWARE,
            description = "启动系统音乐播放器",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_ENVELOPE,
            constantName = "KEYCODE_ENVELOPE",
            labelZh = "打开邮件",
            category = KeyEventCategory.HARDWARE,
            description = "启动系统电子邮件应用",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CONTACTS,
            constantName = "KEYCODE_CONTACTS",
            labelZh = "打开联系人",
            category = KeyEventCategory.HARDWARE,
            description = "启动系统通讯录",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_EXPLORER,
            constantName = "KEYCODE_EXPLORER",
            labelZh = "打开浏览器",
            category = KeyEventCategory.HARDWARE,
            description = "启动默认网络浏览器",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_HELP,
            constantName = "KEYCODE_HELP",
            labelZh = "帮助 (Help)",
            category = KeyEventCategory.HARDWARE,
            description = "打开应用或系统帮助",
        ),

        // ==================== 6. 电视与智能遥控 ====================
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_TV_POWER,
            constantName = "KEYCODE_TV_POWER",
            labelZh = "电视电源 (TV Power)",
            category = KeyEventCategory.TV_REMOTE,
            description = "电视电源开关控制",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_TV_INPUT,
            constantName = "KEYCODE_TV_INPUT",
            labelZh = "电视信号源 (TV Input)",
            category = KeyEventCategory.TV_REMOTE,
            description = "切换电视 HDMI/AV 信号源",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CHANNEL_UP,
            constantName = "KEYCODE_CHANNEL_UP",
            labelZh = "频道 + (Channel Up)",
            category = KeyEventCategory.TV_REMOTE,
            description = "电视/机顶盒电视频道增加",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_CHANNEL_DOWN,
            constantName = "KEYCODE_CHANNEL_DOWN",
            labelZh = "频道 - (Channel Down)",
            category = KeyEventCategory.TV_REMOTE,
            description = "电视/机顶盒电视频道减少",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_LAST_CHANNEL,
            constantName = "KEYCODE_LAST_CHANNEL",
            labelZh = "上一频道 (Last Channel)",
            category = KeyEventCategory.TV_REMOTE,
            description = "切换回到上一个观看的频道",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_GUIDE,
            constantName = "KEYCODE_GUIDE",
            labelZh = "节目指南 (EPG / Guide)",
            category = KeyEventCategory.TV_REMOTE,
            description = "打开电视节目指南",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_INFO,
            constantName = "KEYCODE_INFO",
            labelZh = "节目信息 (Info)",
            category = KeyEventCategory.TV_REMOTE,
            description = "查看当前播放内容详细信息",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_PROG_RED,
            constantName = "KEYCODE_PROG_RED",
            labelZh = "遥控红键 (Red)",
            category = KeyEventCategory.TV_REMOTE,
            description = "遥控器红色快捷按键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_PROG_GREEN,
            constantName = "KEYCODE_PROG_GREEN",
            labelZh = "遥控绿键 (Green)",
            category = KeyEventCategory.TV_REMOTE,
            description = "遥控器绿色快捷按键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_PROG_YELLOW,
            constantName = "KEYCODE_PROG_YELLOW",
            labelZh = "遥控黄键 (Yellow)",
            category = KeyEventCategory.TV_REMOTE,
            description = "遥控器黄色快捷按键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_PROG_BLUE,
            constantName = "KEYCODE_PROG_BLUE",
            labelZh = "遥控蓝键 (Blue)",
            category = KeyEventCategory.TV_REMOTE,
            description = "遥控器蓝色快捷按键",
        ),

        // ==================== 7. 游戏与手柄按键 ====================
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_A,
            constantName = "KEYCODE_BUTTON_A",
            labelZh = "手柄 A 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄 A 确认键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_B,
            constantName = "KEYCODE_BUTTON_B",
            labelZh = "手柄 B 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄 B 取消/后退键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_X,
            constantName = "KEYCODE_BUTTON_X",
            labelZh = "手柄 X 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄 X 功能按键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_Y,
            constantName = "KEYCODE_BUTTON_Y",
            labelZh = "手柄 Y 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄 Y 功能按键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_C,
            constantName = "KEYCODE_BUTTON_C",
            labelZh = "手柄 C 键",
            category = KeyEventCategory.GAMEPAD,
            description = "六键手柄 C 按键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_Z,
            constantName = "KEYCODE_BUTTON_Z",
            labelZh = "手柄 Z 键",
            category = KeyEventCategory.GAMEPAD,
            description = "六键手柄 Z 按键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_L1,
            constantName = "KEYCODE_BUTTON_L1",
            labelZh = "手柄 L1 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄左肩键 L1 (LB)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_R1,
            constantName = "KEYCODE_BUTTON_R1",
            labelZh = "手柄 R1 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄右肩键 R1 (RB)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_L2,
            constantName = "KEYCODE_BUTTON_L2",
            labelZh = "手柄 L2 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄左扳机键 L2 (LT)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_R2,
            constantName = "KEYCODE_BUTTON_R2",
            labelZh = "手柄 R2 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄右扳机键 R2 (RT)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_THUMBL,
            constantName = "KEYCODE_BUTTON_THUMBL",
            labelZh = "左摇杆下压 (L3)",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄左摇杆垂直下压按键 (L3)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_THUMBR,
            constantName = "KEYCODE_BUTTON_THUMBR",
            labelZh = "右摇杆下压 (R3)",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄右摇杆垂直下压按键 (R3)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_START,
            constantName = "KEYCODE_BUTTON_START",
            labelZh = "手柄 Start 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄 Start 开始/暂停键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_SELECT,
            constantName = "KEYCODE_BUTTON_SELECT",
            labelZh = "手柄 Select 键",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄 Select / Back 选择键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_BUTTON_MODE,
            constantName = "KEYCODE_BUTTON_MODE",
            labelZh = "手柄 Mode 键 (Guide)",
            category = KeyEventCategory.GAMEPAD,
            description = "游戏手柄中间西瓜键 / Mode 模式键",
        ),

        // ==================== 8. 功能键 (F1-F12) ====================
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F1,
            constantName = "KEYCODE_F1",
            labelZh = "F1 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F1 功能键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F2,
            constantName = "KEYCODE_F2",
            labelZh = "F2 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F2 功能键 (重命名等)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F3,
            constantName = "KEYCODE_F3",
            labelZh = "F3 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F3 功能键 (查找下一个等)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F4,
            constantName = "KEYCODE_F4",
            labelZh = "F4 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F4 功能键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F5,
            constantName = "KEYCODE_F5",
            labelZh = "F5 功能键 (刷新)",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F5 功能键 (刷新)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F6,
            constantName = "KEYCODE_F6",
            labelZh = "F6 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F6 功能键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F7,
            constantName = "KEYCODE_F7",
            labelZh = "F7 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F7 功能键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F8,
            constantName = "KEYCODE_F8",
            labelZh = "F8 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F8 功能键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F9,
            constantName = "KEYCODE_F9",
            labelZh = "F9 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F9 功能键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F10,
            constantName = "KEYCODE_F10",
            labelZh = "F10 功能键",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F10 功能键",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F11,
            constantName = "KEYCODE_F11",
            labelZh = "F11 功能键 (全屏)",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F11 功能键 (全屏切换)",
        ),
        KeyEventPresetItem(
            keyCode = KeyEvent.KEYCODE_F12,
            constantName = "KEYCODE_F12",
            labelZh = "F12 功能键 (开发者工具)",
            category = KeyEventCategory.FUNCTION_KEYS,
            description = "键盘标准 F12 功能键 (开发者工具/另存为)",
        ),
    )

    private val presetByCode: Map<Int, KeyEventPresetItem> = presets.associateBy { it.keyCode }

    fun findByCode(code: Int): KeyEventPresetItem? = presetByCode[code]

    fun getDisplayName(code: Int, customName: String = ""): String {
        if (customName.isNotBlank()) return customName
        val preset = findByCode(code)
        return if (preset != null) {
            "${preset.labelZh} (${preset.keyCode})"
        } else {
            "KeyCode $code"
        }
    }
}

