package com.slideindex.app.settings

import com.slideindex.app.gesture.GestureAngles
import com.slideindex.app.gesture.GestureRule
import com.slideindex.app.gesture.GestureTriggerMode
import com.slideindex.app.gesture.TriggerHandle
import com.slideindex.app.launcher.QuickLauncherItem
import com.slideindex.app.launcher.QuickLauncherPanel
import com.slideindex.app.shell.ShellCommand

/** 边缘手势与手势会话相关设置子集（窄 Flow 订阅用）。 */
data class GestureSettings(
    val serviceEnabled: Boolean = false,
    val leftEdgeEnabled: Boolean = true,
    val rightEdgeEnabled: Boolean = true,
    val leftEdgeTriggerWidthDp: Float = 20f,
    val rightEdgeTriggerWidthDp: Float = 20f,
    val bottomEdgeTriggerWidthDp: Float = 20f,
    val topEdgeTriggerWidthDp: Float = 20f,
    val leftTriggerTopFraction: Float = 0.30f,
    val rightTriggerTopFraction: Float = 0.30f,
    val leftTriggerHeightFraction: Float = 0.38f,
    val rightTriggerHeightFraction: Float = 0.38f,
    val leftTriggerHandles: List<TriggerHandle> = emptyList(),
    val rightTriggerHandles: List<TriggerHandle> = emptyList(),
    val bottomTriggerHandles: List<TriggerHandle> = emptyList(),
    val topTriggerHandles: List<TriggerHandle> = emptyList(),
    val leftTriggerHandlesLandscape: List<TriggerHandle> = emptyList(),
    val rightTriggerHandlesLandscape: List<TriggerHandle> = emptyList(),
    val bottomTriggerHandlesLandscape: List<TriggerHandle> = emptyList(),
    val topTriggerHandlesLandscape: List<TriggerHandle> = emptyList(),
    val landscapeTriggersInitialized: Boolean = false,
    val gestureRulesLandscape: List<GestureRule> = emptyList(),
    val leftDefaultTriggerModeLandscape: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val rightDefaultTriggerModeLandscape: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val bottomDefaultTriggerModeLandscape: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val topDefaultTriggerModeLandscape: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val interceptSystemBackGesture: Boolean = false,
    val limitMaxInterceptLength: Boolean = false,
    val leftDefaultTriggerMode: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val rightDefaultTriggerMode: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val bottomDefaultTriggerMode: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val topDefaultTriggerMode: GestureTriggerMode = GestureTriggerMode.ON_RELEASE,
    val shortSwipeDistanceDp: Float = 60f,
    val longSwipeDistanceDp: Float = 120f,
    val gestureHintEnabled: Boolean = true,
    val gestureHintStyleId: Int = GestureHintStyle.BUBBLE.id,
    val gestureHintFingerOffsetDp: Float = 0f,
    val animationStyles: AnimationStyles = AnimationStyles(),
    val gestureAngles: GestureAngles = GestureAngles(),
    val indexHeightFraction: Float = 0.42f,
    val appsPerRow: Int = 3,
    val quickLauncherColumnsPerPage: Int = 3,
    val quickLauncherRowsPerPage: Int = 4,
    val panelOpacity: Float = 0.95f,
    val hapticEnabled: Boolean = true,
    val hapticStrengthLevel: Int = HapticStrength.MEDIUM.level,
    val hideTriggerInLandscape: Boolean = false,
    val hideTriggerOnLockScreen: Boolean = false,
    val hideTriggerOnLauncher: Boolean = false,
    val hiddenAppPackages: Set<String> = emptySet(),
    /** “切换上一应用”动作忽略的包名黑名单。 */
    val previousAppExcludedPackages: Set<String> = emptySet(),
    val excludedAppScopes: Map<String, ExcludedAppScopes> = emptyMap(),
    val excludedAppDefaultScopes: ExcludedAppScopes = ExcludedAppScopes.ALL,
    val gestureRules: List<GestureRule> = emptyList(),
    val quickLauncherPanels: List<QuickLauncherPanel> = emptyList(),
    val quickLauncherDisplay: QuickLauncherDisplaySettings = QuickLauncherDisplaySettings(),
    val honeycombLauncher: List<QuickLauncherItem> = emptyList(),
    val honeycombDisplay: HoneycombDisplaySettings = HoneycombDisplaySettings(),
    val fvAppSwitcher: FvAppSwitcherSettings = FvAppSwitcherSettings(),
    val shellCommands: List<ShellCommand> = emptyList(),
    val activityShortcuts: List<com.slideindex.app.activity.ActivityShortcut> = emptyList(),
    val appLaunchPolicyId: Int = AppLaunchPolicy.ALWAYS_FULLSCREEN.id,
    val longPressLaunchDurationMs: Int = 450,
    val widgetPanelPages: List<com.slideindex.app.widget.WidgetPanelPage> = emptyList(),
    val widgetPanelWidthFraction: Float = 0.8f,
    val widgetPanelHeightFraction: Float = 0.55f,
    val widgetPanelTopFraction: Float = 0.15f,
    val widgetPanelBlurEnabled: Boolean = true,
    val widgetPanelBlurRadiusDp: Int = AppSettings.WIDGET_PANEL_BLUR_RADIUS_DEFAULT_DP,
    val debugPerformanceMonitorEnabled: Boolean = false,
) {
    companion object {
        fun from(settings: AppSettings): GestureSettings = GestureSettings(
            serviceEnabled = settings.serviceEnabled,
            leftEdgeEnabled = settings.leftEdgeEnabled,
            rightEdgeEnabled = settings.rightEdgeEnabled,
            leftEdgeTriggerWidthDp = settings.leftEdgeTriggerWidthDp,
            rightEdgeTriggerWidthDp = settings.rightEdgeTriggerWidthDp,
            bottomEdgeTriggerWidthDp = settings.bottomEdgeTriggerWidthDp,
            topEdgeTriggerWidthDp = settings.topEdgeTriggerWidthDp,
            leftTriggerTopFraction = settings.leftTriggerTopFraction,
            rightTriggerTopFraction = settings.rightTriggerTopFraction,
            leftTriggerHeightFraction = settings.leftTriggerHeightFraction,
            rightTriggerHeightFraction = settings.rightTriggerHeightFraction,
            leftTriggerHandles = settings.leftTriggerHandles,
            rightTriggerHandles = settings.rightTriggerHandles,
            bottomTriggerHandles = settings.bottomTriggerHandles,
            topTriggerHandles = settings.topTriggerHandles,
            leftTriggerHandlesLandscape = settings.leftTriggerHandlesLandscape,
            rightTriggerHandlesLandscape = settings.rightTriggerHandlesLandscape,
            bottomTriggerHandlesLandscape = settings.bottomTriggerHandlesLandscape,
            topTriggerHandlesLandscape = settings.topTriggerHandlesLandscape,
            landscapeTriggersInitialized = settings.landscapeTriggersInitialized,
            gestureRulesLandscape = settings.gestureRulesLandscape,
            leftDefaultTriggerModeLandscape = settings.leftDefaultTriggerModeLandscape,
            rightDefaultTriggerModeLandscape = settings.rightDefaultTriggerModeLandscape,
            bottomDefaultTriggerModeLandscape = settings.bottomDefaultTriggerModeLandscape,
            topDefaultTriggerModeLandscape = settings.topDefaultTriggerModeLandscape,
            interceptSystemBackGesture = settings.interceptSystemBackGesture,
            limitMaxInterceptLength = settings.limitMaxInterceptLength,
            leftDefaultTriggerMode = settings.leftDefaultTriggerMode,
            rightDefaultTriggerMode = settings.rightDefaultTriggerMode,
            bottomDefaultTriggerMode = settings.bottomDefaultTriggerMode,
            topDefaultTriggerMode = settings.topDefaultTriggerMode,
            shortSwipeDistanceDp = settings.shortSwipeDistanceDp,
            longSwipeDistanceDp = settings.longSwipeDistanceDp,
            gestureHintEnabled = settings.gestureHintEnabled,
            gestureHintStyleId = settings.gestureHintStyleId,
            gestureHintFingerOffsetDp = settings.gestureHintFingerOffsetDp,
            animationStyles = settings.animationStyles,
            gestureAngles = settings.gestureAngles,
            indexHeightFraction = settings.indexHeightFraction,
            appsPerRow = settings.appsPerRow,
            quickLauncherColumnsPerPage = settings.quickLauncherColumnsPerPage,
            quickLauncherRowsPerPage = settings.quickLauncherRowsPerPage,
            panelOpacity = settings.panelOpacity,
            hapticEnabled = settings.hapticEnabled,
            hapticStrengthLevel = settings.hapticStrengthLevel,
            hideTriggerInLandscape = settings.hideTriggerInLandscape,
            hideTriggerOnLockScreen = settings.hideTriggerOnLockScreen,
            hideTriggerOnLauncher = settings.hideTriggerOnLauncher,
            hiddenAppPackages = settings.hiddenAppPackages,
            previousAppExcludedPackages = settings.previousAppExcludedPackages,
            excludedAppScopes = settings.excludedAppScopes,
            excludedAppDefaultScopes = settings.excludedAppDefaultScopes,
            gestureRules = settings.gestureRules,
            quickLauncherPanels = settings.quickLauncherPanels,
            quickLauncherDisplay = settings.quickLauncherDisplay,
            honeycombLauncher = settings.honeycombLauncher,
            honeycombDisplay = settings.honeycombDisplay,
            fvAppSwitcher = settings.fvAppSwitcher,
            shellCommands = settings.shellCommands,
            activityShortcuts = settings.activityShortcuts,
            appLaunchPolicyId = settings.appLaunchPolicyId,
            longPressLaunchDurationMs = settings.longPressLaunchDurationMs,
            widgetPanelPages = settings.widgetPanelPages,
            widgetPanelWidthFraction = settings.widgetPanelWidthFraction,
            widgetPanelHeightFraction = settings.widgetPanelHeightFraction,
            widgetPanelTopFraction = settings.widgetPanelTopFraction,
            widgetPanelBlurEnabled = settings.widgetPanelBlurEnabled,
            widgetPanelBlurRadiusDp = settings.widgetPanelBlurRadiusDp,
            debugPerformanceMonitorEnabled = settings.debugPerformanceMonitorEnabled,
        )
    }
}
