package com.slideindex.app.settings

import com.slideindex.app.floatball.FloatBallGestureCodec
import com.slideindex.app.floatball.FloatBallGestureType
import com.slideindex.app.gesture.GestureAction

/** 浮层、悬浮球、主题与 App 内外观相关设置子集（窄 Flow 订阅用）。 */
data class OverlaySettings(
    val themeColorArgb: Int = 0xFF6750A4.toInt(),
    val dynamicColorEnabled: Boolean = true,
    val bottomNavGlassEnabled: Boolean = true,
    val bottomNavBlurRadiusDp: Float = BottomNavBlurDefaults.DEFAULT_RADIUS_DP,
    val freeWindowEnabled: Boolean = false,
    val freeWindowModeId: Int = FreeWindowMode.detectDefault().id,
    val freeWindowWidthFraction: Float = 0.8f,
    val freeWindowHeightFraction: Float = 0.55f,
    val freeWindowLeftFraction: Float = 0.1f,
    val freeWindowTopFraction: Float = 0.15f,
    val floatingPointerSensitivityFraction: Float = 0.52f,
    val floatingPointerJoystickDiameterPx: Float = 275f,
    val floatingPointerPointerDiameterPx: Float = 100f,
    val floatingPointerDesignId: String = FloatingPointerDesignIds.RING,
    val floatingPointerRingThicknessPx: Float = 12f,
    val floatingPointerDotDiameterPx: Float = 15f,
    val floatingPointerRingColorArgb: Int = 0xFFFFFFFF.toInt(),
    val floatingPointerFillColorArgb: Int = 0x19000000,
    val floatingPointerDotColorArgb: Int = 0xFFFFFFFF.toInt(),
    val floatingPointerClickVisualFeedbackEnabled: Boolean = true,
    val floatingPointerClickHapticEnabled: Boolean = true,
    val floatingPointerRippleColorArgb: Int = 0xFFFD746C.toInt(),
    val floatingPointerRippleSizeDp: Float = 80f,
    val floatingPointerRippleDurationMs: Int = 500,
    val floatingPointerTrailTypeId: Int = FloatingPointerTrailType.HIGH_DETAIL.id,
    val floatingPointerTrailDurationMs: Int = 150,
    val floatingPointerTrailColorArgb: Int = 0x66FF5252,
    val floatingPointerHideWhenJoystickReleased: Boolean = false,
    val floatingPointerClickDistanceThresholdDp: Float = 6f,
    val floatingPointerJoystickInnerColorArgb: Int = 0x80FFFFFF.toInt(),
    val floatingPointerJoystickOuterColorArgb: Int = 0x80C0C0C0.toInt(),
    val floatingPointerJoystickGradientRadiusFraction: Float = 1f,
    val floatingPointerHideOnOutsideClick: Boolean = true,
    val floatingPointerHideOnQuickSwipe: Boolean = true,
    val floatingPointerHideWhenIdle: Boolean = true,
    val floatingPointerIdleHideDelayMs: Int = 3000,
    val floatingPointerJoystickLongPressAction: GestureAction = GestureAction.OpenFloatingPointerRadialMenu,
    val floatingPointerRadialAlwaysVisible: Boolean = false,
    val floatingPointerRadialLongPressMs: Int = 500,
    val floatingPointerRadialOuterDiameterPx: Float = 440f,
    val floatingPointerRadialInnerDiameterPx: Float = 192f,
    val floatingPointerRadialOuterColorArgb: Int = 0xE62B3D4F.toInt(),
    val floatingPointerRadialInnerColorArgb: Int = 0xE61A1A28.toInt(),
    val floatingPointerRadialDividerThicknessPx: Float = 4f,
    val floatingPointerRadialDividerColorArgb: Int = 0x22FFFFFF,
    val floatingPointerRadialIconSizeFraction: Float = 0.85f,
    val floatingPointerRadialIconColorArgb: Int = 0xFFFFFFFF.toInt(),
    val floatingPointerRadialSlotActions: List<GestureAction> = FloatingPointerRadialMenuCodec.defaultSlots(),
    val floatingPointerEdgeThresholdDp: Float = 30f,
    val floatingPointerEdgePreviewSensitivity: Int = 3,
    val floatingPointerEdgePreviewGlowSize: Int = 4,
    val floatingPointerEdgePreviewShowIcon: Boolean = true,
    val floatingPointerEdgeVisualSizeDp: Float = 0f,
    val floatingPointerEdgeVisualOpacity: Int = 75,
    val floatingPointerEdgeVisualColorArgb: Int = 0xFFFD746C.toInt(),
    val floatingPointerEdgeActionsConfig: FloatingPointerEdgeActionsConfig =
        FloatingPointerEdgeActionsCodec.defaultConfig(),
    val floatBallEnabled: Boolean = false,
    val floatBallSizeDp: Float = 48f,
    val floatBallPickCrossArmDp: Float = 7.5f,
    val floatBallOpacity: Float = 0.88f,
    val floatBallVisibleFraction: Float = 1f,
    val floatBallCustomCenterXFraction: Float = 0.92f,
    val floatBallPositionYFraction: Float = 0.55f,
    val floatBallOcrFallbackEnabled: Boolean = true,
    val floatBallOcrModelId: String = "",
    val ocrDownloadWifiOnly: Boolean = true,
    val floatBallPointerSpeedFraction: Float = 0.35f,
    val floatBallPositionMode: FloatBallPositionMode = FloatBallPositionMode.RIGHT,
    val floatBallActiveSide: FloatBallSide = FloatBallSide.RIGHT,
    val floatBallLineHeightFraction: Float = 0.08f,
    val floatBallLineWidthFraction: Float = 0.04f,
    val floatBallLineOpacity: Float = 0.9f,
    val floatBallGestureActions: Map<FloatBallGestureType, GestureAction> = FloatBallGestureCodec.defaultActions(),
    val floatBallStyleType: FloatBallStyleType = FloatBallStyleType.DEFAULT,
    val floatBallCustomImageUri: String = "",
    val floatBallSlideshowUris: List<String> = emptyList(),
    val floatBallGifUri: String = "",
    val floatBallPickOffsetDp: Float = 48f,
    val floatBallPickTextSizeSp: Float = 15f,
    val floatBallPickBottomTransitionFraction: Float = 0.22f,
    val floatBallPickTextFirstPanel: Boolean = false,
    val floatBallPickPanelEnterAnimationMs: Int = 64,
    val floatBallPickPanelExitAnimationMs: Int = 64,
    val floatBallPointerSlopDp: Float = 8f,
    val floatBallDownSwipeShortPercent: Float = 200f,
    val floatBallSideSwipeShortPercent: Float = 320f,
    val floatBallUpSwipeShortPercent: Float = 256f,
    val floatBallInstantTranslate: Boolean = false,
    val floatBallTranslateEngine: FloatBallTranslateEngine = FloatBallTranslateEngine.GOOGLE,
    val floatBallTranslateTargetLang: String = "zh-CN",
    val floatBallImageSearchPickPanelTransparency: Float = 0.65f,
    val shareImageOcrHistoryEnabled: Boolean = true,
    val clipboardBackgroundMonitoring: Boolean = true,
    val clipboardBackgroundMonitoringPath: ClipboardMonitoringPath = ClipboardMonitoringPath.LOGCAT,
    val clipboardScreenshotMonitoring: Boolean = false,
    val clipboardLsposedExtraWhitelist: Set<String> = emptySet(),
    val clipboardHistoryMaxEntries: Int = 100,
    val defaultImageViewerPackage: String? = null,
    val searchEngines: List<SearchEngineConfig> = SearchEngineCatalog.defaultEngines(),
    val searchEngineGridColumns: Int = 5,
    val searchEngineGridRows: Int = 2,
    val searchEngineShowLabels: Boolean = true,
    val searchPanelDefaultEngineId: String? = null,
    val searchPanelInputBehavior: SearchPanelInputBehavior = SearchPanelInputBehavior.KEEP,
    val aggregatedImageSearchEngines: List<AggregatedImageSearchEngineConfig> =
        AppSettings.defaultAggregatedImageSearchEngines(),
    val cornerGestureSettings: CornerGestureSettings = CornerGestureSettings(),
) {
    companion object {
        fun from(settings: AppSettings): OverlaySettings = OverlaySettings(
            themeColorArgb = settings.themeColorArgb,
            dynamicColorEnabled = settings.dynamicColorEnabled,
            bottomNavGlassEnabled = settings.bottomNavGlassEnabled,
            bottomNavBlurRadiusDp = settings.bottomNavBlurRadiusDp,
            freeWindowEnabled = settings.freeWindowEnabled,
            freeWindowModeId = settings.freeWindowModeId,
            freeWindowWidthFraction = settings.freeWindowWidthFraction,
            freeWindowHeightFraction = settings.freeWindowHeightFraction,
            freeWindowLeftFraction = settings.freeWindowLeftFraction,
            freeWindowTopFraction = settings.freeWindowTopFraction,
            floatingPointerSensitivityFraction = settings.floatingPointerSensitivityFraction,
            floatingPointerJoystickDiameterPx = settings.floatingPointerJoystickDiameterPx,
            floatingPointerPointerDiameterPx = settings.floatingPointerPointerDiameterPx,
            floatingPointerDesignId = settings.floatingPointerDesignId,
            floatingPointerRingThicknessPx = settings.floatingPointerRingThicknessPx,
            floatingPointerDotDiameterPx = settings.floatingPointerDotDiameterPx,
            floatingPointerRingColorArgb = settings.floatingPointerRingColorArgb,
            floatingPointerFillColorArgb = settings.floatingPointerFillColorArgb,
            floatingPointerDotColorArgb = settings.floatingPointerDotColorArgb,
            floatingPointerClickVisualFeedbackEnabled = settings.floatingPointerClickVisualFeedbackEnabled,
            floatingPointerClickHapticEnabled = settings.floatingPointerClickHapticEnabled,
            floatingPointerRippleColorArgb = settings.floatingPointerRippleColorArgb,
            floatingPointerRippleSizeDp = settings.floatingPointerRippleSizeDp,
            floatingPointerRippleDurationMs = settings.floatingPointerRippleDurationMs,
            floatingPointerTrailTypeId = settings.floatingPointerTrailTypeId,
            floatingPointerTrailDurationMs = settings.floatingPointerTrailDurationMs,
            floatingPointerTrailColorArgb = settings.floatingPointerTrailColorArgb,
            floatingPointerHideWhenJoystickReleased = settings.floatingPointerHideWhenJoystickReleased,
            floatingPointerClickDistanceThresholdDp = settings.floatingPointerClickDistanceThresholdDp,
            floatingPointerJoystickInnerColorArgb = settings.floatingPointerJoystickInnerColorArgb,
            floatingPointerJoystickOuterColorArgb = settings.floatingPointerJoystickOuterColorArgb,
            floatingPointerJoystickGradientRadiusFraction = settings.floatingPointerJoystickGradientRadiusFraction,
            floatingPointerHideOnOutsideClick = settings.floatingPointerHideOnOutsideClick,
            floatingPointerHideOnQuickSwipe = settings.floatingPointerHideOnQuickSwipe,
            floatingPointerHideWhenIdle = settings.floatingPointerHideWhenIdle,
            floatingPointerIdleHideDelayMs = settings.floatingPointerIdleHideDelayMs,
            floatingPointerJoystickLongPressAction = settings.floatingPointerJoystickLongPressAction,
            floatingPointerRadialAlwaysVisible = settings.floatingPointerRadialAlwaysVisible,
            floatingPointerRadialLongPressMs = settings.floatingPointerRadialLongPressMs,
            floatingPointerRadialOuterDiameterPx = settings.floatingPointerRadialOuterDiameterPx,
            floatingPointerRadialInnerDiameterPx = settings.floatingPointerRadialInnerDiameterPx,
            floatingPointerRadialOuterColorArgb = settings.floatingPointerRadialOuterColorArgb,
            floatingPointerRadialInnerColorArgb = settings.floatingPointerRadialInnerColorArgb,
            floatingPointerRadialDividerThicknessPx = settings.floatingPointerRadialDividerThicknessPx,
            floatingPointerRadialDividerColorArgb = settings.floatingPointerRadialDividerColorArgb,
            floatingPointerRadialIconSizeFraction = settings.floatingPointerRadialIconSizeFraction,
            floatingPointerRadialIconColorArgb = settings.floatingPointerRadialIconColorArgb,
            floatingPointerRadialSlotActions = settings.floatingPointerRadialSlotActions,
            floatingPointerEdgeThresholdDp = settings.floatingPointerEdgeThresholdDp,
            floatingPointerEdgePreviewSensitivity = settings.floatingPointerEdgePreviewSensitivity,
            floatingPointerEdgePreviewGlowSize = settings.floatingPointerEdgePreviewGlowSize,
            floatingPointerEdgePreviewShowIcon = settings.floatingPointerEdgePreviewShowIcon,
            floatingPointerEdgeVisualSizeDp = settings.floatingPointerEdgeVisualSizeDp,
            floatingPointerEdgeVisualOpacity = settings.floatingPointerEdgeVisualOpacity,
            floatingPointerEdgeVisualColorArgb = settings.floatingPointerEdgeVisualColorArgb,
            floatingPointerEdgeActionsConfig = settings.floatingPointerEdgeActionsConfig,
            floatBallEnabled = settings.floatBallEnabled,
            floatBallSizeDp = settings.floatBallSizeDp,
            floatBallPickCrossArmDp = settings.floatBallPickCrossArmDp,
            floatBallOpacity = settings.floatBallOpacity,
            floatBallVisibleFraction = settings.floatBallVisibleFraction,
            floatBallCustomCenterXFraction = settings.floatBallCustomCenterXFraction,
            floatBallPositionYFraction = settings.floatBallPositionYFraction,
            floatBallOcrFallbackEnabled = settings.floatBallOcrFallbackEnabled,
            floatBallOcrModelId = settings.floatBallOcrModelId,
            ocrDownloadWifiOnly = settings.ocrDownloadWifiOnly,
            floatBallPointerSpeedFraction = settings.floatBallPointerSpeedFraction,
            floatBallPositionMode = settings.floatBallPositionMode,
            floatBallActiveSide = settings.floatBallActiveSide,
            floatBallLineHeightFraction = settings.floatBallLineHeightFraction,
            floatBallLineWidthFraction = settings.floatBallLineWidthFraction,
            floatBallLineOpacity = settings.floatBallLineOpacity,
            floatBallGestureActions = settings.floatBallGestureActions,
            floatBallStyleType = settings.floatBallStyleType,
            floatBallCustomImageUri = settings.floatBallCustomImageUri,
            floatBallSlideshowUris = settings.floatBallSlideshowUris,
            floatBallGifUri = settings.floatBallGifUri,
            floatBallPickOffsetDp = settings.floatBallPickOffsetDp,
            floatBallPickTextSizeSp = settings.floatBallPickTextSizeSp,
            floatBallPickBottomTransitionFraction = settings.floatBallPickBottomTransitionFraction,
            floatBallPickTextFirstPanel = settings.floatBallPickTextFirstPanel,
            floatBallPickPanelEnterAnimationMs = settings.floatBallPickPanelEnterAnimationMs,
            floatBallPickPanelExitAnimationMs = settings.floatBallPickPanelExitAnimationMs,
            floatBallPointerSlopDp = settings.floatBallPointerSlopDp,
            floatBallDownSwipeShortPercent = settings.floatBallDownSwipeShortPercent,
            floatBallSideSwipeShortPercent = settings.floatBallSideSwipeShortPercent,
            floatBallUpSwipeShortPercent = settings.floatBallUpSwipeShortPercent,
            floatBallInstantTranslate = settings.floatBallInstantTranslate,
            floatBallTranslateEngine = settings.floatBallTranslateEngine,
            floatBallTranslateTargetLang = settings.floatBallTranslateTargetLang,
            floatBallImageSearchPickPanelTransparency = settings.floatBallImageSearchPickPanelTransparency,
            shareImageOcrHistoryEnabled = settings.shareImageOcrHistoryEnabled,
            clipboardBackgroundMonitoring = settings.clipboardBackgroundMonitoring,
            clipboardBackgroundMonitoringPath = settings.clipboardBackgroundMonitoringPath,
            clipboardScreenshotMonitoring = settings.clipboardScreenshotMonitoring,
            clipboardLsposedExtraWhitelist = settings.clipboardLsposedExtraWhitelist,
            clipboardHistoryMaxEntries = settings.clipboardHistoryMaxEntries,
            defaultImageViewerPackage = settings.defaultImageViewerPackage,
            searchEngines = settings.searchEngines,
            searchEngineGridColumns = settings.searchEngineGridColumns,
            searchEngineGridRows = settings.searchEngineGridRows,
            searchEngineShowLabels = settings.searchEngineShowLabels,
            searchPanelDefaultEngineId = settings.searchPanelDefaultEngineId,
            searchPanelInputBehavior = settings.searchPanelInputBehavior,
            aggregatedImageSearchEngines = settings.aggregatedImageSearchEngines,
            cornerGestureSettings = settings.cornerGestureSettings,
        )
    }
}

object BottomNavBlurDefaults {
    const val DEFAULT_RADIUS_DP = 24f
    const val MIN_RADIUS_DP = 0f
    const val MAX_RADIUS_DP = 32f
}

object PickPanelSlideAnimationDefaults {
    const val MIN_MS = 0
    const val MAX_MS = 400
    const val DEFAULT_MS = 64

    fun coerceMs(value: Int): Int = value.coerceIn(MIN_MS, MAX_MS)
}

/** 是否走 Haze 采样/合成（毛玻璃总开关开启且模糊半径 > 0）。 */
fun OverlaySettings.usesBottomNavHaze(): Boolean =
    bottomNavGlassEnabled && bottomNavBlurRadiusDp > BottomNavBlurDefaults.MIN_RADIUS_DP
