package com.slideindex.app.settings

import android.content.Context
import androidx.annotation.StringRes
import com.slideindex.app.settings.R

import java.util.UUID

enum class PresetSearchCategory {
    All,
    General,
    Social,
    VideoMedia,
    ShoppingLife,
    ToolsDev,
}

data class PresetSearchEngine(
    val presetId: String,
    @StringRes val nameRes: Int,
    val category: PresetSearchCategory,
    @StringRes val descriptionRes: Int,
    val engineType: SearchEngineType = SearchEngineType.DIRECT_LINK,
    val searchLink: String? = null,
    val externJumpLink: String? = null,
    val externJumpPackage: String? = null,
    val targetPackage: String? = null,
    val targetActivity: String? = null,
    val autoInputEnter: Boolean = true,
    val iconAssetFileName: String? = null,
) {
    fun localizedName(context: Context): String = context.getString(nameRes)

    fun localizedDescription(context: Context): String = context.getString(descriptionRes)

    fun toSearchEngineConfig(context: Context, sortOrder: Int): SearchEngineConfig = SearchEngineConfig(
        id = UUID.randomUUID().toString(),
        name = context.getString(nameRes),
        engineType = engineType,
        iconType = if (iconAssetFileName != null) SearchIconType.URI else SearchIconType.OTHER,
        iconPath = iconAssetFileName?.let { "preset_search_icons/$it" },
        searchLink = searchLink,
        externJumpLink = externJumpLink,
        externJumpPackage = externJumpPackage,
        targetPackage = targetPackage,
        targetActivity = targetActivity,
        autoInputEnter = autoInputEnter,
        showInPickPanel = true,
        sortOrder = sortOrder,
    )
}

object PresetSearchEngineCatalog {

    fun allPresets(): List<PresetSearchEngine> = listOf(
        // 1. 通用搜索 (General)
        PresetSearchEngine(
            presetId = "preset-google",
            nameRes = R.string.preset_se_google_name,
            category = PresetSearchCategory.General,
            descriptionRes = R.string.preset_se_google_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.google.com/search?q=%s",
            iconAssetFileName = "google.png",
        ),
        PresetSearchEngine(
            presetId = "preset-baidu",
            nameRes = R.string.preset_se_baidu_name,
            category = PresetSearchCategory.General,
            descriptionRes = R.string.preset_se_baidu_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.baidu.com/s?word=%s",
            iconAssetFileName = "baidu.png",
        ),
        PresetSearchEngine(
            presetId = "preset-bing",
            nameRes = R.string.preset_se_bing_name,
            category = PresetSearchCategory.General,
            descriptionRes = R.string.preset_se_bing_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.bing.com/search?q=%s",
        ),
        PresetSearchEngine(
            presetId = "preset-quark",
            nameRes = R.string.preset_se_quark_name,
            category = PresetSearchCategory.General,
            descriptionRes = R.string.preset_se_quark_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "intent://m.quark.cn/s?q=%s#Intent;scheme=https;package=com.quark.browser;end",
            targetPackage = "com.quark.browser",
            iconAssetFileName = "quark.png",
        ),

        // 2. 社交社区 (Social)
        PresetSearchEngine(
            presetId = "preset-wechat",
            nameRes = R.string.preset_se_wechat_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_wechat_desc,
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.tencent.mm",
            targetActivity = "com.tencent.mm.plugin.fts.ui.FTSMainUI",
        ),
        PresetSearchEngine(
            presetId = "preset-qq",
            nameRes = R.string.preset_se_qq_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_qq_desc,
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.tencent.mobileqq",
            targetActivity = "com.tencent.mobileqq.search.activity.UniteSearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-weibo",
            nameRes = R.string.preset_se_weibo_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_weibo_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "sinaweibo://searchall?q=%s",
            targetPackage = "com.sina.weibo",
            iconAssetFileName = "weibo.png",
        ),
        PresetSearchEngine(
            presetId = "preset-weibo-see",
            nameRes = R.string.preset_se_weibo_see_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_weibo_see_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "sinaweibo://searchall?q=%s",
            targetPackage = "com.caij.see",
            iconAssetFileName = "weibo.png",
        ),
        PresetSearchEngine(
            presetId = "preset-weibo-share",
            nameRes = R.string.preset_se_weibo_share_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_weibo_share_desc,
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            searchLink = "sinaweibo://searchall?q=%s",
            externJumpLink = "sinaweibo://searchall?q=%s",
            externJumpPackage = "com.hengye.share",
            targetPackage = "com.hengye.share",
            targetActivity = "com.hengye.share.module.search.SearchActivity",
            iconAssetFileName = "weibo.png",
        ),
        PresetSearchEngine(
            presetId = "preset-zhihu",
            nameRes = R.string.preset_se_zhihu_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_zhihu_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "zhihu://search?q=%s",
            targetPackage = "com.zhihu.android",
            iconAssetFileName = "zhihu.png",
        ),
        PresetSearchEngine(
            presetId = "preset-xhs",
            nameRes = R.string.preset_se_xhs_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_xhs_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "xhsdiscover://search/result?keyword=%s",
            targetPackage = "com.xingin.xhs",
            iconAssetFileName = "xhs.png",
        ),
        PresetSearchEngine(
            presetId = "preset-tieba",
            nameRes = R.string.preset_se_tieba_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_tieba_desc,
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.baidu.tieba",
            targetActivity = "com.baidu.tieba.mainentrance.NewSquareSearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-tieba-lite",
            nameRes = R.string.preset_se_tieba_lite_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_tieba_lite_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tblite://search",
            externJumpLink = "tblite://search",
            targetActivity = "com.huanchengfly.tieba.post.MainActivityV2",
            iconAssetFileName = "tieba_lite.png",
        ),
        PresetSearchEngine(
            presetId = "preset-coolapk",
            nameRes = R.string.preset_se_coolapk_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_coolapk_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            externJumpLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            targetPackage = "com.coolapk.market",
            iconAssetFileName = "coolapk.png",
        ),
        PresetSearchEngine(
            presetId = "preset-coolapk-third",
            nameRes = R.string.preset_se_coolapk_third_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_coolapk_third_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            externJumpLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            targetPackage = "com.example.c001apk.compose",
            iconAssetFileName = "coolapk.png",
        ),
        PresetSearchEngine(
            presetId = "preset-twitter",
            nameRes = R.string.preset_se_twitter_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_twitter_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://mobile.twitter.com/search?q=%s&src=typed_query",
            iconAssetFileName = "twitter.png",
        ),
        PresetSearchEngine(
            presetId = "preset-telegram",
            nameRes = R.string.preset_se_telegram_name,
            category = PresetSearchCategory.Social,
            descriptionRes = R.string.preset_se_telegram_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tg://search?query=%s",
        ),

        // 3. 视频影音与音乐 (VideoMedia)
        PresetSearchEngine(
            presetId = "preset-bilibili",
            nameRes = R.string.preset_se_bilibili_name,
            category = PresetSearchCategory.VideoMedia,
            descriptionRes = R.string.preset_se_bilibili_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "bilibili://search?keyword=%q",
            externJumpLink = "bilibili://search?keyword=%q",
            targetPackage = "tv.danmaku.bili",
            iconAssetFileName = "piliplus.png",
        ),
        PresetSearchEngine(
            presetId = "preset-douyin",
            nameRes = R.string.preset_se_douyin_name,
            category = PresetSearchCategory.VideoMedia,
            descriptionRes = R.string.preset_se_douyin_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "snssdk1128://search/result?keyword=%s",
            targetPackage = "com.ss.android.ugc.aweme",
            iconAssetFileName = "douyin.png",
        ),
        PresetSearchEngine(
            presetId = "preset-youtube",
            nameRes = R.string.preset_se_youtube_name,
            category = PresetSearchCategory.VideoMedia,
            descriptionRes = R.string.preset_se_youtube_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.youtube.com/results?search_query=%s",
            targetPackage = "com.google.android.youtube",
            iconAssetFileName = "youtube.png",
        ),
        PresetSearchEngine(
            presetId = "preset-netease-music",
            nameRes = R.string.preset_se_netease_music_name,
            category = PresetSearchCategory.VideoMedia,
            descriptionRes = R.string.preset_se_netease_music_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "orpheus://nm/search/result?keyword=%s",
            targetPackage = "com.netease.cloudmusic",
        ),
        PresetSearchEngine(
            presetId = "preset-qq-music",
            nameRes = R.string.preset_se_qq_music_name,
            category = PresetSearchCategory.VideoMedia,
            descriptionRes = R.string.preset_se_qq_music_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "qqmusic://qq.com/ui/search?p={\"query\":\"%s\"}",
            targetPackage = "com.tencent.qqmusic",
        ),
        PresetSearchEngine(
            presetId = "preset-luna-music",
            nameRes = R.string.preset_se_luna_music_name,
            category = PresetSearchCategory.VideoMedia,
            descriptionRes = R.string.preset_se_luna_music_desc,
            engineType = SearchEngineType.EXTERN_JUMP_LINK,
            externJumpLink = "luna://luna.com/search",
            externJumpPackage = "com.luna.music",
            targetPackage = "com.luna.music",
            targetActivity = "com.luna.biz.main.main.MainActivity",
        ),

        // 4. 生活购物与支付 (ShoppingLife)
        PresetSearchEngine(
            presetId = "preset-alipay",
            nameRes = R.string.preset_se_alipay_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_alipay_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "alipays://platformapi/startapp?appId=20001003&keyword=%s#Intent;component=com.eg.android.AlipayGphone/com.alipay.mobile.quinox.LauncherActivity.alias;B.directly=true;B.fromDesktop=true;end",
            targetPackage = "com.eg.android.AlipayGphone",
        ),
        PresetSearchEngine(
            presetId = "preset-taobao",
            nameRes = R.string.preset_se_taobao_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_taobao_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tbopen://m.taobao.com/tbopen/index.html?h5Url=https://s.taobao.com/search?q=%s",
            targetPackage = "com.taobao.taobao",
            iconAssetFileName = "taobao.png",
        ),
        PresetSearchEngine(
            presetId = "preset-taobao-order",
            nameRes = R.string.preset_se_taobao_order_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_taobao_order_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tbopen://m.taobao.com/tbopen/index.html?h5Url=https://market.m.taobao.com/app/dinamic/h5-tb-olist/index.html?condition={\"wordTerm\":\"%s\"}",
            targetPackage = "com.taobao.taobao",
            iconAssetFileName = "taobao.png",
        ),
        PresetSearchEngine(
            presetId = "preset-jd",
            nameRes = R.string.preset_se_jd_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_jd_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "openapp.jdmobile://virtual?params={\"category\":\"jump\",\"des\":\"search\",\"keyWord\":\"%s\"}",
            targetPackage = "com.jingdong.app.mall",
            iconAssetFileName = "jd.png",
        ),
        PresetSearchEngine(
            presetId = "preset-pdd",
            nameRes = R.string.preset_se_pdd_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_pdd_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "pinduoduo://com.xunmeng.pinduoduo/search_result.html?search_key=%s",
            targetPackage = "com.xunmeng.pinduoduo",
            iconAssetFileName = "pdd.png",
        ),
        PresetSearchEngine(
            presetId = "preset-1688",
            nameRes = R.string.preset_se_1688_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_1688_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "wireless1688://ma.m.1688.com/fromwap?tonative=https://m.1688.com/offer_search/-6D7033.html?keywords=%s",
            targetPackage = "com.alibaba.wireless",
        ),
        PresetSearchEngine(
            presetId = "preset-idlefish",
            nameRes = R.string.preset_se_idlefish_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_idlefish_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "fleamarket://search_items?keyword=%s",
            targetPackage = "com.taobao.idlefish",
            targetActivity = "com.taobao.idlefish.search_implement.SearchActiveActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-meituan",
            nameRes = R.string.preset_se_meituan_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_meituan_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "imeituan://www.meituan.com/search?q=%s",
            targetPackage = "com.sankuai.meituan",
        ),
        PresetSearchEngine(
            presetId = "preset-amap",
            nameRes = R.string.preset_se_amap_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_amap_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "androidamap://poi?sourceApplication=softname&keywords=%s",
            targetPackage = "com.autonavi.minimap",
        ),
        PresetSearchEngine(
            presetId = "preset-baidumap",
            nameRes = R.string.preset_se_baidumap_name,
            category = PresetSearchCategory.ShoppingLife,
            descriptionRes = R.string.preset_se_baidumap_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "bdapp://map/geocoder?src=andr.baidu.openAPIdemo&address=%s",
            targetPackage = "com.baidu.BaiduMap",
        ),

        // 5. 工具、开发与 AI 助手 (ToolsDev)
        PresetSearchEngine(
            presetId = "preset-doubao",
            nameRes = R.string.preset_se_doubao_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_doubao_desc,
            engineType = SearchEngineType.SHARE_TO_APP,
            targetPackage = "com.larus.nova",
            targetActivity = "com.larus.home.impl.MainActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-tongyi",
            nameRes = R.string.preset_se_tongyi_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_tongyi_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tongyi://page/h5?url=https://www.myquark.cn?entry=chat_share&qk_biz=ai_chat&qk_module=home&qk_params={\"query\":\"%q\"}",
            targetPackage = "com.aliyun.tongyi",
            targetActivity = "com.ucpro.MainActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-xiaoai",
            nameRes = R.string.preset_se_xiaoai_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_xiaoai_desc,
            engineType = SearchEngineType.SHARE_TO_APP,
            targetPackage = "com.miui.voiceassist",
            targetActivity = "com.xiaomi.voiceassistant.ShareReceiverActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-eudic",
            nameRes = R.string.preset_se_eudic_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_eudic_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "eudic://dict/%s",
            targetPackage = "com.qianyan.eudic",
        ),
        PresetSearchEngine(
            presetId = "preset-legado",
            nameRes = R.string.preset_se_legado_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_legado_desc,
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "io.legado.app.release",
            targetActivity = "io.legado.app.ui.book.search.SearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-file-info",
            nameRes = R.string.preset_se_file_info_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_file_info_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "search://com.ktls.fileinfo/search?q=%s",
            targetPackage = "com.ktls.fileinfo",
        ),
        PresetSearchEngine(
            presetId = "preset-115",
            nameRes = R.string.preset_se_115_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_115_desc,
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.ylmf.androidclient",
            targetActivity = "com.main.disk.file.file.activity.DiskSearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-market",
            nameRes = R.string.preset_se_market_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_market_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "market://search?q=%s",
            targetPackage = "com.xiaomi.market",
            targetActivity = "com.xiaomi.market.ui.SearchActivityPhone",
        ),
        PresetSearchEngine(
            presetId = "preset-google-play",
            nameRes = R.string.preset_se_google_play_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_google_play_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "http://play.google.com/store/search?q=%s&c=apps",
            targetPackage = "com.android.vending",
            iconAssetFileName = "google_play.png",
        ),
        PresetSearchEngine(
            presetId = "preset-appshare",
            nameRes = R.string.preset_se_appshare_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_appshare_desc,
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "info.muge.appshare",
            targetActivity = "info.muge.appshare.MainActivity",
            iconAssetFileName = "appshare.png",
        ),
        PresetSearchEngine(
            presetId = "preset-github",
            nameRes = R.string.preset_se_github_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_github_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://github.com/search?q=%s&type=repositories",
            iconAssetFileName = "github.png",
        ),
        PresetSearchEngine(
            presetId = "preset-missav",
            nameRes = R.string.preset_se_missav_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_missav_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://missav.ai/cn/search/%s",
            iconAssetFileName = "missav.png",
        ),
        PresetSearchEngine(
            presetId = "preset-tel",
            nameRes = R.string.preset_se_tel_name,
            category = PresetSearchCategory.ToolsDev,
            descriptionRes = R.string.preset_se_tel_desc,
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tel://%s",
        ),
    )
}
