package com.slideindex.app.settings

import java.util.UUID

enum class PresetSearchCategory {
    All,
    General,
    Social,
    VideoMedia,
    ShoppingLife,
    ToolsDev,
}

data class PresetSearchEngine(
    val presetId: String,
    val name: String,
    val category: PresetSearchCategory,
    val description: String,
    val engineType: SearchEngineType = SearchEngineType.DIRECT_LINK,
    val searchLink: String? = null,
    val externJumpLink: String? = null,
    val externJumpPackage: String? = null,
    val targetPackage: String? = null,
    val targetActivity: String? = null,
    val autoInputEnter: Boolean = true,
    val iconAssetFileName: String? = null,
) {
    fun toSearchEngineConfig(sortOrder: Int): SearchEngineConfig = SearchEngineConfig(
        id = UUID.randomUUID().toString(),
        name = name,
        engineType = engineType,
        iconType = if (iconAssetFileName != null) SearchIconType.URI else SearchIconType.OTHER,
        iconPath = iconAssetFileName?.let { "preset_search_icons/$it" },
        searchLink = searchLink,
        externJumpLink = externJumpLink,
        externJumpPackage = externJumpPackage,
        targetPackage = targetPackage,
        targetActivity = targetActivity,
        autoInputEnter = autoInputEnter,
        showInPickPanel = true,
        sortOrder = sortOrder,
    )
}

object PresetSearchEngineCatalog {

    fun allPresets(): List<PresetSearchEngine> = listOf(
        // 1. 通用搜索 (General)
        PresetSearchEngine(
            presetId = "preset-google",
            name = "Google",
            category = PresetSearchCategory.General,
            description = "谷歌全网网页与资讯搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.google.com/search?q=%s",
            iconAssetFileName = "google.png",
        ),
        PresetSearchEngine(
            presetId = "preset-baidu",
            name = "百度",
            category = PresetSearchCategory.General,
            description = "百度网页与热点搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.baidu.com/s?word=%s",
            iconAssetFileName = "baidu.png",
        ),
        PresetSearchEngine(
            presetId = "preset-bing",
            name = "Bing 必应",
            category = PresetSearchCategory.General,
            description = "微软必应搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.bing.com/search?q=%s",
        ),
        PresetSearchEngine(
            presetId = "preset-quark",
            name = "夸克搜索",
            category = PresetSearchCategory.General,
            description = "调用夸克 App 进行智能搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "intent://m.quark.cn/s?q=%s#Intent;scheme=https;package=com.quark.browser;end",
            targetPackage = "com.quark.browser",
            iconAssetFileName = "quark.png",
        ),

        // 2. 社交社区 (Social)
        PresetSearchEngine(
            presetId = "preset-wechat",
            name = "微信搜索",
            category = PresetSearchCategory.Social,
            description = "跳转微信全局搜一搜界面",
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.tencent.mm",
            targetActivity = "com.tencent.mm.plugin.fts.ui.FTSMainUI",
        ),
        PresetSearchEngine(
            presetId = "preset-qq",
            name = "QQ 搜索",
            category = PresetSearchCategory.Social,
            description = "跳转 QQ 全局统一搜索界面",
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.tencent.mobileqq",
            targetActivity = "com.tencent.mobileqq.search.activity.UniteSearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-weibo",
            name = "微博",
            category = PresetSearchCategory.Social,
            description = "官方微博客户端热搜与内容搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "sinaweibo://searchall?q=%s",
            targetPackage = "com.sina.weibo",
            iconAssetFileName = "weibo.png",
        ),
        PresetSearchEngine(
            presetId = "preset-weibo-see",
            name = "微博 (See)",
            category = PresetSearchCategory.Social,
            description = "第三方微博 See 客户端搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "sinaweibo://searchall?q=%s",
            targetPackage = "com.caij.see",
            iconAssetFileName = "weibo.png",
        ),
        PresetSearchEngine(
            presetId = "preset-weibo-share",
            name = "微博 (Share)",
            category = PresetSearchCategory.Social,
            description = "第三方微博 Share 客户端搜索",
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            searchLink = "sinaweibo://searchall?q=%s",
            externJumpLink = "sinaweibo://searchall?q=%s",
            externJumpPackage = "com.hengye.share",
            targetPackage = "com.hengye.share",
            targetActivity = "com.hengye.share.module.search.SearchActivity",
            iconAssetFileName = "weibo.png",
        ),
        PresetSearchEngine(
            presetId = "preset-zhihu",
            name = "知乎",
            category = PresetSearchCategory.Social,
            description = "知乎问答与专栏文章搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "zhihu://search?q=%s",
            targetPackage = "com.zhihu.android",
            iconAssetFileName = "zhihu.png",
        ),
        PresetSearchEngine(
            presetId = "preset-xhs",
            name = "小红书",
            category = PresetSearchCategory.Social,
            description = "小红书种草笔记与生活经验搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "xhsdiscover://search/result?keyword=%s",
            targetPackage = "com.xingin.xhs",
            iconAssetFileName = "xhs.png",
        ),
        PresetSearchEngine(
            presetId = "preset-tieba",
            name = "百度贴吧",
            category = PresetSearchCategory.Social,
            description = "官方贴吧进吧与全吧帖子搜索",
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.baidu.tieba",
            targetActivity = "com.baidu.tieba.mainentrance.NewSquareSearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-tieba-lite",
            name = "贴吧 Lite",
            category = PresetSearchCategory.Social,
            description = "第三方贴吧 Lite 极速搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tblite://search",
            externJumpLink = "tblite://search",
            targetActivity = "com.huanchengfly.tieba.post.MainActivityV2",
            iconAssetFileName = "tieba_lite.png",
        ),
        PresetSearchEngine(
            presetId = "preset-coolapk",
            name = "酷安",
            category = PresetSearchCategory.Social,
            description = "酷安数码社区应用与动态搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            externJumpLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            targetPackage = "com.coolapk.market",
            iconAssetFileName = "coolapk.png",
        ),
        PresetSearchEngine(
            presetId = "preset-coolapk-third",
            name = "酷安 (泛酷客)",
            category = PresetSearchCategory.Social,
            description = "第三方泛酷客客户端搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            externJumpLink = "coolmarket://com.coolapk.market/search?searchValue=%s",
            targetPackage = "com.example.c001apk.compose",
            iconAssetFileName = "coolapk.png",
        ),
        PresetSearchEngine(
            presetId = "preset-twitter",
            name = "Twitter / X",
            category = PresetSearchCategory.Social,
            description = "Twitter / X 全球推文搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://mobile.twitter.com/search?q=%s&src=typed_query",
            iconAssetFileName = "twitter.png",
        ),
        PresetSearchEngine(
            presetId = "preset-telegram",
            name = "Telegram",
            category = PresetSearchCategory.Social,
            description = "Telegram 消息与频道搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tg://search?query=%s",
        ),

        // 3. 视频影音与音乐 (VideoMedia)
        PresetSearchEngine(
            presetId = "preset-bilibili",
            name = "B站 (官方)",
            category = PresetSearchCategory.VideoMedia,
            description = "哔哩哔哩视频与番剧搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "bilibili://search?keyword=%q",
            externJumpLink = "bilibili://search?keyword=%q",
            targetPackage = "tv.danmaku.bili",
            iconAssetFileName = "piliplus.png",
        ),
        PresetSearchEngine(
            presetId = "preset-douyin",
            name = "抖音",
            category = PresetSearchCategory.VideoMedia,
            description = "抖音短视频与直播搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "snssdk1128://search/result?keyword=%s",
            targetPackage = "com.ss.android.ugc.aweme",
            iconAssetFileName = "douyin.png",
        ),
        PresetSearchEngine(
            presetId = "preset-youtube",
            name = "YouTube",
            category = PresetSearchCategory.VideoMedia,
            description = "YouTube 视频与频道搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://www.youtube.com/results?search_query=%s",
            targetPackage = "com.google.android.youtube",
            iconAssetFileName = "youtube.png",
        ),
        PresetSearchEngine(
            presetId = "preset-netease-music",
            name = "网易云音乐",
            category = PresetSearchCategory.VideoMedia,
            description = "网易云音乐歌曲与歌单检索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "orpheus://nm/search/result?keyword=%s",
            targetPackage = "com.netease.cloudmusic",
        ),
        PresetSearchEngine(
            presetId = "preset-qq-music",
            name = "QQ 音乐",
            category = PresetSearchCategory.VideoMedia,
            description = "QQ 音乐歌曲与歌手搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "qqmusic://qq.com/ui/search?p={\"query\":\"%s\"}",
            targetPackage = "com.tencent.qqmusic",
        ),
        PresetSearchEngine(
            presetId = "preset-luna-music",
            name = "汽水音乐",
            category = PresetSearchCategory.VideoMedia,
            description = "抖音官方汽水音乐搜索",
            engineType = SearchEngineType.EXTERN_JUMP_LINK,
            externJumpLink = "luna://luna.com/search",
            externJumpPackage = "com.luna.music",
            targetPackage = "com.luna.music",
            targetActivity = "com.luna.biz.main.main.MainActivity",
        ),

        // 4. 生活购物与支付 (ShoppingLife)
        PresetSearchEngine(
            presetId = "preset-alipay",
            name = "支付宝",
            category = PresetSearchCategory.ShoppingLife,
            description = "支付宝全局生活服务与小程序搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "alipays://platformapi/startapp?appId=20001003&keyword=%s#Intent;component=com.eg.android.AlipayGphone/com.alipay.mobile.quinox.LauncherActivity.alias;B.directly=true;B.fromDesktop=true;end",
            targetPackage = "com.eg.android.AlipayGphone",
        ),
        PresetSearchEngine(
            presetId = "preset-taobao",
            name = "淘宝",
            category = PresetSearchCategory.ShoppingLife,
            description = "淘宝商品与比价搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tbopen://m.taobao.com/tbopen/index.html?h5Url=https://s.taobao.com/search?q=%s",
            targetPackage = "com.taobao.taobao",
            iconAssetFileName = "taobao.png",
        ),
        PresetSearchEngine(
            presetId = "preset-taobao-order",
            name = "淘宝订单",
            category = PresetSearchCategory.ShoppingLife,
            description = "搜索淘宝已买到的历史宝贝与订单",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tbopen://m.taobao.com/tbopen/index.html?h5Url=https://market.m.taobao.com/app/dinamic/h5-tb-olist/index.html?condition={\"wordTerm\":\"%s\"}",
            targetPackage = "com.taobao.taobao",
            iconAssetFileName = "taobao.png",
        ),
        PresetSearchEngine(
            presetId = "preset-jd",
            name = "京东",
            category = PresetSearchCategory.ShoppingLife,
            description = "京东商城正品商品搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "openapp.jdmobile://virtual?params={\"category\":\"jump\",\"des\":\"search\",\"keyWord\":\"%s\"}",
            targetPackage = "com.jingdong.app.mall",
            iconAssetFileName = "jd.png",
        ),
        PresetSearchEngine(
            presetId = "preset-pdd",
            name = "拼多多",
            category = PresetSearchCategory.ShoppingLife,
            description = "拼多多百亿补贴与优惠商品搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "pinduoduo://com.xunmeng.pinduoduo/search_result.html?search_key=%s",
            targetPackage = "com.xunmeng.pinduoduo",
            iconAssetFileName = "pdd.png",
        ),
        PresetSearchEngine(
            presetId = "preset-1688",
            name = "1688",
            category = PresetSearchCategory.ShoppingLife,
            description = "阿里巴巴 1688 源头批发货源搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "wireless1688://ma.m.1688.com/fromwap?tonative=https://m.1688.com/offer_search/-6D7033.html?keywords=%s",
            targetPackage = "com.alibaba.wireless",
        ),
        PresetSearchEngine(
            presetId = "preset-idlefish",
            name = "闲鱼",
            category = PresetSearchCategory.ShoppingLife,
            description = "闲鱼二手闲置与好物搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "fleamarket://search_items?keyword=%s",
            targetPackage = "com.taobao.idlefish",
            targetActivity = "com.taobao.idlefish.search_implement.SearchActiveActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-meituan",
            name = "美团",
            category = PresetSearchCategory.ShoppingLife,
            description = "美团外卖、美食与生活团购搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "imeituan://www.meituan.com/search?q=%s",
            targetPackage = "com.sankuai.meituan",
        ),
        PresetSearchEngine(
            presetId = "preset-amap",
            name = "高德地图",
            category = PresetSearchCategory.ShoppingLife,
            description = "高德地点、路线与周边生活搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "androidamap://poi?sourceApplication=softname&keywords=%s",
            targetPackage = "com.autonavi.minimap",
        ),
        PresetSearchEngine(
            presetId = "preset-baidumap",
            name = "百度地图",
            category = PresetSearchCategory.ShoppingLife,
            description = "百度地图地点与路线检索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "bdapp://map/geocoder?src=andr.baidu.openAPIdemo&address=%s",
            targetPackage = "com.baidu.BaiduMap",
        ),

        // 5. 工具、开发与 AI 助手 (ToolsDev)
        PresetSearchEngine(
            presetId = "preset-doubao",
            name = "豆包",
            category = PresetSearchCategory.ToolsDev,
            description = "字节跳动豆包 AI 对话与智能搜索",
            engineType = SearchEngineType.SHARE_TO_APP,
            targetPackage = "com.larus.nova",
            targetActivity = "com.larus.home.impl.MainActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-tongyi",
            name = "通义千问",
            category = PresetSearchCategory.ToolsDev,
            description = "阿里通义千问大模型智能问答",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tongyi://page/h5?url=https://www.myquark.cn?entry=chat_share&qk_biz=ai_chat&qk_module=home&qk_params={\"query\":\"%q\"}",
            targetPackage = "com.aliyun.tongyi",
            targetActivity = "com.ucpro.MainActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-xiaoai",
            name = "小爱同学",
            category = PresetSearchCategory.ToolsDev,
            description = "小米 / MIUI 小爱语音助手查词问答",
            engineType = SearchEngineType.SHARE_TO_APP,
            targetPackage = "com.miui.voiceassist",
            targetActivity = "com.xiaomi.voiceassistant.ShareReceiverActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-eudic",
            name = "欧路词典",
            category = PresetSearchCategory.ToolsDev,
            description = "外语学习查词神器，取词直接查释义",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "eudic://dict/%s",
            targetPackage = "com.qianyan.eudic",
        ),
        PresetSearchEngine(
            presetId = "preset-legado",
            name = "开源阅读 (Legado)",
            category = PresetSearchCategory.ToolsDev,
            description = "开源阅读 App 书名与书源搜书",
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "io.legado.app.release",
            targetActivity = "io.legado.app.ui.book.search.SearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-file-info",
            name = "秒搜文件",
            category = PresetSearchCategory.ToolsDev,
            description = "本地极速文件搜索神器",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "search://com.ktls.fileinfo/search?q=%s",
            targetPackage = "com.ktls.fileinfo",
        ),
        PresetSearchEngine(
            presetId = "preset-115",
            name = "115 网盘",
            category = PresetSearchCategory.ToolsDev,
            description = "115 云盘文件与资源搜索",
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "com.ylmf.androidclient",
            targetActivity = "com.main.disk.file.file.activity.DiskSearchActivity",
        ),
        PresetSearchEngine(
            presetId = "preset-market",
            name = "应用商店",
            category = PresetSearchCategory.ToolsDev,
            description = "小米/系统应用商店搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "market://search?q=%s",
            targetPackage = "com.xiaomi.market",
            targetActivity = "com.xiaomi.market.ui.SearchActivityPhone",
        ),
        PresetSearchEngine(
            presetId = "preset-google-play",
            name = "Google Play",
            category = PresetSearchCategory.ToolsDev,
            description = "Google Play 商店官方应用与游戏检索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "http://play.google.com/store/search?q=%s&c=apps",
            targetPackage = "com.android.vending",
            iconAssetFileName = "google_play.png",
        ),
        PresetSearchEngine(
            presetId = "preset-appshare",
            name = "APP分享",
            category = PresetSearchCategory.ToolsDev,
            description = "AppShare 应用市场搜索",
            engineType = SearchEngineType.JUMP_TO_ACTIVITY,
            targetPackage = "info.muge.appshare",
            targetActivity = "info.muge.appshare.MainActivity",
            iconAssetFileName = "appshare.png",
        ),
        PresetSearchEngine(
            presetId = "preset-github",
            name = "GitHub",
            category = PresetSearchCategory.ToolsDev,
            description = "GitHub 开源项目与代码仓库搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://github.com/search?q=%s&type=repositories",
            iconAssetFileName = "github.png",
        ),
        PresetSearchEngine(
            presetId = "preset-missav",
            name = "MissAV",
            category = PresetSearchCategory.ToolsDev,
            description = "MissAV 影视搜索",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "https://missav.ai/cn/search/%s",
            iconAssetFileName = "missav.png",
        ),
        PresetSearchEngine(
            presetId = "preset-tel",
            name = "电话拨号",
            category = PresetSearchCategory.ToolsDev,
            description = "选中电话号码一键调起系统拨号盘",
            engineType = SearchEngineType.DIRECT_LINK,
            searchLink = "tel://%s",
        ),
    )
}
