#!/usr/bin/env python3
"""Misc hardcoded UI strings to migrate (non-KeyEventPreset)."""

MISC_STRINGS = [
    # VlmOcrSettingsScreen
    ("vlm_ocr_connection_test_failed_saved", "连接测试未通过，配置已保存，请检查接口设置"),
    ("vlm_ocr_save_cd", "保存"),
    ("vlm_ocr_section_api", "接口连接"),
    ("vlm_ocr_default_endpoint", "默认端点为：%1$s"),
    ("vlm_ocr_section_model", "模型选择与测试"),
    ("vlm_ocr_recommended_models", "快捷选择该服务商推荐型号："),
    ("vlm_ocr_saved_custom_models", "已保存的自定义型号："),
    ("vlm_ocr_testing_connection", "正在测试连接..."),
    ("vlm_ocr_test_connection", "测试连接"),
    ("vlm_ocr_connection_success_prefix", "连接成功"),
    ("vlm_ocr_section_prompt", "识别提示词 (System Prompt)"),
    ("vlm_ocr_custom_prompt_title", "自定义专属提示词"),
    ("vlm_ocr_custom_prompt_enabled", "已启用专属覆盖，优先使用下方自定义内容"),
    ("vlm_ocr_custom_prompt_disabled", "已暂停专属覆盖，草稿仍保留在本地"),
    ("vlm_ocr_custom_prompt_label", "专属 System Prompt"),
    ("vlm_ocr_load_generic_template", "载入通用模板"),
    ("vlm_ocr_custom_prompt_hint", "关闭开关时暂停专属覆盖；开启后可为 %1$s 独立微调。只有点击「载入通用模板」才会写入通用内容。"),
    # OCR errors
    ("ocr_error_no_model_selected", "未选择 OCR 模型"),
    ("ocr_error_recognition_failed", "识别异常：%1$s"),
    ("ocr_error_unknown", "未知错误"),
    # OcrModelSettingsScreen
    ("ocr_engine_status_ready", "已就绪"),
    ("ocr_engine_status_not_installed", "未安装"),
    ("ocr_engine_installed_summary", "底层 C++ 推理库 · %1$s%2$s"),
    ("ocr_engine_not_installed_summary", "未安装底层运行库 (%1$s)，离线识别不可用"),
    ("ocr_engine_manage", "管理"),
    ("ocr_engine_install", "安装"),
    ("ocr_common_config_title", "通用配置"),
    ("ocr_common_prompt_customized", "已自定义全局通用内容"),
    ("ocr_common_prompt_default", "当前使用出厂默认"),
    ("ocr_global_system_prompt", "全局通用提示词 (System Prompt)"),
    ("ocr_edit", "编辑"),
    ("ocr_restore_default", "恢复默认"),
    ("ocr_global_system_prompt_field", "全局通用 System Prompt"),
    ("ocr_model_status_active", "使用中"),
    ("ocr_model_status_ready", "已就绪"),
    ("ocr_model_status_not_configured", "未配置"),
    ("ocr_model_summary_custom_prompt", "当前模型: %1$s · 专属提示词"),
    ("ocr_model_summary_inherit_global", "当前模型: %1$s · 继承全局"),
    ("ocr_settings", "设置"),
    ("ocr_configure", "配置"),
    # ForegroundActivityInspector
    ("foreground_inspector_app_name", "应用名称: %1$s"),
    ("foreground_inspector_package_name", "包名: %1$s"),
    # TaskManagerShell
    ("shell_downgrade_hint", "提示:已将root降权至shell\n"),
    ("shell_downgrade_failed", "无法降级到 adb/shell 身份（Shizuku 当前以 Root 运行）。\n请改用 adb/无线调试方式启动 Shizuku。"),
    # TaskManagerUtil
    ("privileged_task_skipped_main_thread", "主线程跳过特权任务"),
    ("privileged_no_root", "无 Root 权限"),
    # AppCarouselSwitcher
    ("app_carousel_cancel_hint", "移至屏幕顶部或底部松手取消"),
    # ExtensionHub
    ("extension_about_subtitle", "版本、更新与隐私协议"),
    # ExternalInvocationCatalog
    ("external_invocation_keyword_example", " \"关键词\""),
    # SearchPanel
    ("search_panel_aggregated_image_search", "聚合搜图"),
    ("search_panel_aggregated_image_icon", "聚"),
    # PickResultPanelChrome
    ("pick_result_copy_selection", "复制选中"),
    # MiuixScaffold - check if exists
    # FloatBallPickSettings
    ("image_viewer_loading", "加载中…"),
    ("image_viewer_default_title", "默认图片查看器"),
    # QuickLauncher
    ("quick_launcher_default_folder_name", "文件夹"),
    ("quick_launcher_add_title", "快速启动器 · 添加快捷项"),
    ("quick_launcher_my_shortcuts", "我的直达"),
    ("quick_launcher_preset_shortcuts", "预设快捷方式库"),
    ("quick_launcher_multi_select_hint", "可勾选多个快捷项添加到面板"),
    # PresetShortcutRepository
    ("preset_shortcut_category_other", "其他快捷指令"),
    ("preset_app_alipay", "支付宝"),
    ("preset_app_coolapk", "酷安"),
    ("preset_app_wechat", "微信"),
    ("preset_app_meituan", "美团"),
    ("preset_app_taobao", "淘宝"),
    ("preset_app_bilibili", "哔哩哔哩"),
    ("preset_app_netease_music", "网易云音乐"),
    ("preset_app_unionpay", "云闪付"),
    ("preset_app_system_settings", "系统设置"),
    ("preset_app_miui_security", "手机管家/安全中心"),
    ("preset_app_pinduoduo", "拼多多"),
    ("preset_app_jd", "京东"),
    ("preset_app_douyin", "抖音"),
    # KnownAppShortcuts - WeChat/Alipay shortcuts
    ("shortcut_scan", "扫一扫"),
    ("shortcut_my_qr", "我的二维码"),
    ("shortcut_receive_pay", "收付款"),
    ("shortcut_cainiao", "菜鸟"),
    ("shortcut_ant_forest", "蚂蚁森林"),
    ("shortcut_receive_code", "收款码"),
    ("shortcut_pay_code", "付款码"),
    ("shortcut_bus_code", "乘车码"),
    # GestureActionPickerSearch - Chinese search aliases (keep as string arrays or individual)
    ("gesture_search_carousel_1", "应用切换器"),
    ("gesture_search_carousel_2", "卡片切换"),
    ("gesture_search_carousel_3", "应用轮播"),
    ("gesture_search_carousel_4", "任务轮播"),
    ("gesture_search_carousel_5", "多任务"),
    ("gesture_search_fingertip_1", "指尖轮盘"),
    ("gesture_search_fingertip_2", "轮盘"),
    ("gesture_search_fingertip_3", "径向"),
    ("gesture_search_screen_off_1", "伪息屏"),
    ("gesture_search_screen_off_2", "息屏挂机"),
    ("gesture_search_screen_off_3", "保持唤醒"),
    ("gesture_search_screen_off_4", "防烧屏"),
    ("gesture_search_screen_off_5", "黑屏挂机"),
    ("gesture_search_pin_1", "钉到屏幕"),
    ("gesture_search_pin_2", "屏幕便签"),
    ("gesture_search_pin_3", "置顶图片"),
    ("gesture_search_pin_4", "悬浮便签"),
    ("gesture_search_pin_5", "置顶"),
    ("gesture_search_fg_activity_1", "前台活动"),
    ("gesture_search_fg_activity_2", "前台活动探测"),
    ("gesture_search_fg_activity_3", "当前页面"),
    ("gesture_search_fg_activity_4", "包名查看"),
    ("gesture_search_app_info_1", "当前应用信息"),
    ("gesture_search_app_info_2", "应用详情"),
    ("gesture_search_app_info_3", "应用管理"),
    ("gesture_search_internet_1", "网络连接面板"),
    ("gesture_search_internet_2", "网络面板"),
    ("gesture_search_internet_3", "移动数据"),
    ("gesture_search_volume_1", "原生声音调节"),
    ("gesture_search_volume_2", "原生音量"),
    ("gesture_search_volume_3", "音量面板"),
    ("gesture_search_keyevent_1", "模拟按键"),
    ("gesture_search_keyevent_2", "按键模拟"),
    # KeyEvent fallback
    ("keyevent_fallback_name", "KeyCode %1$d"),
]
